# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('date_pub', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='the_press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.Press'),
        ),
    ]
